# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3944e6a6d31f929d5d6a93915cf04256193463d81255544c612914660d626e5db772ad489fd3881418f81792e91f822669d412fe032083f3c66b719da61a34c5

test:
  secret_key_base: 669b466677308cfdf4a6fa0a7ed45a8463ed043508c69e325f2bd428df20368f3c2733a6afc46ee7d657d7514148d66074af49690848d9efe83e25d63ec9395c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
